version: "3.8"

services:

  postgres:
    image: postgres:latest
    container_name: lumos-postgres
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: lumos-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: lumos-redis-insight
    restart: always
    expose:
      - "5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: lumos-grafana
    expose:
      - "3000"
    env_file:
      - .env.prod
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  loki:
    image: grafana/loki:2.9.3
    container_name: lumos-loki
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml -log.level=warn
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.9.3
    container_name: lumos-promtail
    volumes:
      - /var/log:/var/log # 시스템 로그 접근
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # 도커 로그 위치
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: lumos-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: lumos-node-exporter
    expose:
      - "9100"
    networks:
      - app-network
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: lumos-cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--docker_only=true"
      - "--housekeeping_interval=10s"
      - "--store_container_labels=true"
      - "--allow_dynamic_housekeeping=true"
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
  grafana_data:
  redis_data:
  redis-insight-data:

networks:
  app-network:
    external: true
