services:

  # Spring Cloud Gateway
  gateway-service:
    image: itsanisland/lumos-gateway-service:blue
    container_name: lumos-gateway-service-blue
    ports:
      - "8081:8080"
    env_file:
      - .env.prod
    depends_on:
      - gesture-sensor-service
      - auth-service
      - member-service
      - smartthings-service
    networks:
      - app-network

  # 제스처 센서 서비스
  gesture-sensor-service:
    image: itsanisland/lumos-gesture-sensor-service:blue
    container_name: lumos-gesture-sensor-service-blue
    expose:
      - "8080"  # 내부 통신용
    env_file:
      - .env.prod
      - ./gesture-sensor-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  
  # 인증 서비스
  auth-service:
    image: itsanisland/lumos-auth-service:blue
    container_name: lumos-auth-service-blue
    expose:
      - "8080"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  
  # 회원 서비스
  member-service:
    image: itsanisland/lumos-member-service:blue
    container_name: lumos-member-service-blue
    expose:
      - "8080"
    env_file:
      - ./member-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  
  # 기기 서비스
  device-service:
    image: itsanisland/lumos-device-service:blue
    container_name: lumos-device-service-blue
    expose:
      - "8080"
    env_file:
      - ./device-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  
  # 제스처 서비스
  gesture-service:
    image: itsanisland/lumos-gesture-service:blue
    container_name: lumos-gesture-service-blue
    expose:
      - "8080"
    env_file:
      - ./gesture-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  
  # 루틴 서비스
  routine-service:
    image: itsanisland/lumos-routine-service:blue
    container_name: lumos-routine-service-blue
    expose:
      - "8080"
    env_file:
      - ./routine-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # SmartThings 서비스
  smartthings-service:
    image: itsanisland/lumos-smartthings-service:blue
    container_name: lumos-smartthings-service-blue
    expose:
      - "3000"
    env_file:
      - ./smartthings-service/.env
    volumes:
      - ./smartthings-service/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    external: true