spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092  # 컨테이너 내부에서 Kafka로 접근 시

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

sensor:
  csv-upload-enabled: true