global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['lumos-node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['lumos-cadvisor:8080']
  
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gateway-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'
      
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-auth-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'
        
  - job_name: 'member-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-member-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'
      
  - job_name: 'gesture-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gesture-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'

  - job_name: 'gesture-sensor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gesture-sensor-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'
      
  - job_name: 'device-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-device-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'

  - job_name: 'routine-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-routine-service:8080']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        regex: '/lumos-(.*)-service'
        target_label: job
        replacement: '$1'