global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['lumos-node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['lumos-cadvisor:8080']
  
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gateway-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: gateway-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-gateway
      
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-auth-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: auth-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-auth
        
  - job_name: 'member-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-member-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: member-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-member
      
  - job_name: 'gesture-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gesture-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: gesture-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-gesture

  - job_name: 'gesture-sensor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-gesture-sensor-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: gesture-sensor-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-gesture-sensor
      
  - job_name: 'device-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-device-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: device-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-device

  - job_name: 'routine-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lumos-routine-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: routine-service
      - source_labels: [__address__]
        target_label: instance
        replacement: lumos-routine