spring:
  application:
    name: gateway-service

  jackson:
    time-zone: ${TZ}

  config:
    import: "optional:configserver:"

  webflux:
    base-path: /
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

springdoc:
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
    urls:
      - name: gesture-sensor-service
        url: /gesture/v3/api-docs
      - name: smartthings-service
        url: /smart/v3/api-docs/