spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: member-service
          uri: http://member-service:8080
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: device-service
          uri: http://device-service:8080
          predicates:
            - Path=/device/**
          filters:
            - StripPrefix=1
        - id: gesture-sensor-service
          uri: http://gesture-sensor-service:8080
          predicates:
            - Path=/gesture/**    # prefix로 구분
          filters:
            - StripPrefix=1
        - id: smartthings-service
          uri: http://smartthings-service:3000
          predicates:
            - Path=/smart/**
          filters:
            - StripPrefix=1