spring:
  application:
    name: gateway-service

  config:
    import: "optional:configserver:"

  webflux:
    base-path: /
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
