spring:
  cloud:
    gateway:
      routes:
        - id: gesture-sensor-service
          uri: http://gesture-sensor-service:8080
          predicates:
            - Path=/gesture/**    # prefix로 구분
          filters:
            - StripPrefix=1
        - id: smartthings-service
          uri: http://smartthings-service:3000
          predicates:
            - Path=/smart/**
          filters:
            - StripPrefix=1