spring:
  cloud:
    gateway:
      routes:
        - id: gesture-sensor
          uri: http://localhost:8081
          predicates:
            - Path=/gesture/**
          filters:
            - StripPrefix=1
        - id: smartthings-service
          uri: http://localhost:3000
          predicates:
            - Path=/smart/**
          filters:
            - StripPrefix=1

server:
  port: 8080

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: gesture-sensor-service
        url: http://localhost:8081/v3/api-docs
      - name: smartthings-service
        url: http://localhost:3000/v3/api-docs