spring:
  cloud:
    gateway:
      routes:
        - id: gesture-sensor
          uri: http://localhost:8081
          predicates:
            - Path=/gesture/**
          filters:
            - StripPrefix=1
        - id: smartthings-service
          uri: http://localhost:3000
          predicates:
            - Path=/smart/**
          filters:
            - StripPrefix=1

server:
  port: 8080

springdoc:
  swagger-ui:
    urls[0]:
      name: gesture-sensor-service
      url: http://localhost:8081/v3/api-docs
    urls[1]:
      name: smartthings-service
      url: http://localhost:3000/v3/api-docs
    use-root-path: true
