spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: member-service
          uri: http://localhost:8086
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: device-service
          uri: http://localhost:8082
          predicates:
            - Path=/device/**
          filters:
            - StripPrefix=1
        - id: gesture-service
          uri: http://localhost:8083
          predicates:
            - Path=/gesture/**
          filters:
            - StripPrefix=1
        - id: gesture-sensor-service
          uri: http://localhost:8081
          predicates:
            - Path=/gesture-sensor/**
          filters:
            - StripPrefix=1
        - id: routine-service
          uri: http://localhost:8084
          predicates:
            - Path=/routine/**
          filters:
            - StripPrefix=1
        - id: smartthings-service
          uri: http://localhost:3000
          predicates:
            - Path=/smart/**
          filters:
            - StripPrefix=1

server:
  port: 8080