spring:
  application:
    name: gateway-service

  jackson:
    time-zone: ${TZ}

  profiles:
    active: prod

  config:
    import: "optional:configserver:"

  webflux:
    base-path: /
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
