spring:
  application:
    name: routine-service

  config:
    import: "optional:configserver:"

  webflux:
    base-path: /
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

  sql:
      init:
        mode: always
        data-locations: classpath:data.sql