spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

smartthings:
  api:
    base-url: http://smartthings-service:3000

gesture:
  service:
    url: http://gesture-service:8080

device:
  service:
    url: http://device-service:8080