spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

smartthings:
  service:
    url: https://k12d103.p.ssafy.io/smart

gesture:
  service:
    url: http://localhost:8083

device:
  service:
    url: http://localhost:8082